#!/bin/bash

# Get total disk space
total=$(df -h | awk '$NF=="/"{print $2}' | sed 's/G//')

# Get free disk space
free=$(df -h | awk '$NF=="/"{print $4}' | sed 's/G//')

# Calculate percentage used


if [ "$1" == "total" ]; then
  echo $total
elif [ "$1" == "free" ]; then 
  echo $free  
elif [ "$1" == "used" ]; then
  used=$(($total - $free))
  echo $used
elif [ "$1" == "pct" ]; then
  pct=$((($free) * 100 / $total))
  echo $pct
else
  echo "Usage: $0 {total|free|used|pct}" >&2
  exit 1
fi
